version: "3.9"

services:
  backend:
    image: ghcr.io/${GHCR_OWNER:-VuongHuuAn}/vha-store-backend:${TAG:-feat-docker}
    pull_policy: always
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: "5000"
      MONGODB_URL: ${MONGODB_URL}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}

  frontend:
    image: ghcr.io/${GHCR_OWNER:-VuongHuuAn}/vha-store-frontend:${TAG:-feat-docker}
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3001:80"
